using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CjbfU8CwebAPI.Models.Fj
{
    public class FJ_billvo_children
    {
        public double bbhl { get; set; }//本币
        public string cinventoryid { get; set; }//存货编码
        public string ddh { get; set; }//订单号
        public double dfbbje { get; set; }//贷方本币金...
        public double dfbbsj { get; set; }//贷方本币税...
        public double dfbbwsje { get; set; }//贷方本币无...
        public double dfshl { get; set; }//贷方数量
        public double dfybje { get; set; }//贷方原币金...
        public double dfybsj { get; set; }//贷方原币税...
        public double dfybwsje { get; set; }//贷方原币无...
        public double dj { get; set; }//单价
        public string fph { get; set; }//发票号
        public double hsdj { get; set; }//含税单价
        public double jfbbje { get; set; }//借方本币金...
        public double jfbbsj { get; set; }//借方本币税...
        public double jfshl { get; set; }//借方数量
        public string  jfybje { get; set; }//借方原币金...
        public double jfybsj { get; set; }//借方原币税...
        public double jfybwsje { get; set; }//借方原币无...
        public string jobid { get; set; }//项目编码
        public int kslb { get; set; }//扣税类别
        public double sl { get; set; }//税率
        public string szxmid { get; set; }//收支项目编...

        public string tradertype { get; set; }//交易对象类型
        public double wbfbbje { get; set; }//借方本币无...
        public string zy { get; set; }//摘要
        public string zyx1 { get; set; }//自定义项1
        public string zyx10 { get; set; }//自定义项1...
        public string zyx11 { get; set; }//自定义项1...
        public string zyx12 { get; set; }//自定义项1...
        public string zyx13 { get; set; }//自定义项1...
        public string zyx14 { get; set; }//自定义项1...
        public string zyx15 { get; set; }//自定义项1...
        public string zyx16 { get; set; }//自定义项1...
        public string zyx17 { get; set; }//自定义项1...
        public string zyx18 { get; set; }//自定义项1...
        public string zyx19 { get; set; }//自定义项1...
        public string zyx2 { get; set; }//自定义项2
        public string zyx20 { get; set; }//自定义项2...
        public string zyx21 { get; set; }//自定义项2...
        public string zyx22 { get; set; }//自定义项2...
        public string zyx23 { get; set; }//自定义项2...
        public string zyx24 { get; set; }//自定义项2...
        public string zyx25 { get; set; }//自定义项2...
        public string zyx26 { get; set; }//自定义项2...
        public string zyx27 { get; set; }//自定义项2...
        public string zyx28 { get; set; }//自定义项2...
        public string zyx29 { get; set; }//自定义项2...
        public string zyx3 { get; set; }//自定义项3
        public string zyx30 { get; set; }//自定义项3...
        public string zyx4 { get; set; }//自定义项4
        public string zyx5 { get; set; }//自定义项5
        public string zyx6 { get; set; }//自定义项6
        public string zyx7 { get; set; }//自定义项7
        public string zyx8 { get; set; }//自定义项8
        public string zyx9 { get; set; }//自定义项9
        public string dfyhzh { get; set; }//收款银行账...
        public string kxyt { get; set; }
    }
}